### PR TITLE
Added a few apps.

### PR DESCRIPTION
**Pull request by SylveonBottle**
Added apps:
1.) Minecraft (popular game) | https://minecraft.net/en-us/
2.) Tixati (light-weight torrenting) | https://www.tixati.com/
3.) Discord (super-duper popular communication app for gamers & more) | https://discordapp.com/

### CODE REVIEW

**Comment by SylveonBottle** [comment]
Also, just wanted to say that this script is absolutely amazing. I normally have problems installing the graphics driver and window manager (normally because I keep editing the example in lightdm and not the actual setting part, derp), this script was able to detect & fly right through it all. I was even able to use it to download codecs and some of my first-to-add softwares. Not to mention the fact that I've never installed a window manager as easy as typing a number and pressing enter!

Installation of Arch Linux (with Deepin & proper graphics drivers) normally takes me around 4-6 hours. This script helped me install everything in less than an hour, the only hiccup being that I typed an invalid mirror address and had to manually remove it.

**Comment by helmuthdu** [comment]
Glad you like it. 😄 
Can you just make a little change in this pr? Can you also updated the lilo.automode file adding those new apps there too?
Cheers,

**Comment by SylveonBottle** [comment]
Updated upon request. Maybe I'll come back to this in the future and add a few more things, like wget or mouespad and notepadqq, etc.

**Comment by SylveonBottle** [comment]
Lastly, I'd recommend adding an option for the video card detection for ati in lilo.sh. Older AMD graphics drivers are no longer compatible with the latest radeon drivers, so users must blacklist radeon. 
https://wiki.archlinux.org/index.php/AMD_Catalyst#Loading_the_module_at_boot

**Pull request merged**
