### PR TITLE
Some Additions & Fixes To lilo including README.md.

### PR DESCRIPTION
**Pull request by Uniminin**
This Pull Request Containts all commits to the additions, changes and fixes to lilo Base Script and README.md. Thank you!

### CODE REVIEW

**Comment by Uniminin** [comment]
@helmuthdu all of your scripts requires shellcheck passes as well. Note that.

**Comment by helmuthdu** [comment]
hey @Uniminin, thanks for your contribution. Looks good.
Just one more thing, can you also update the lilo.automode file with these changes?

**Comment by Uniminin** [comment]
@helmuthdu sure. i'll do it today.

**Comment by Uniminin** [comment]
@helmuthdu Ping! Done.

**Comment by helmuthdu** [comment]
Good job! 👍

**Pull request merged**
