### PR TITLE
[Testing needed] fifo: Improvements

### PR DESCRIPTION
**Pull request by AvinashReddy3108**
- Dynamically list keymap files instead of hardcoding them.
https://wiki.archlinux.org/index.php/Linux_console/Keyboard_configuration#Listing_keymaps

- Dynamically list mirror countries and country codes using `reflector` (included with recent official ISOs)

### CODE REVIEW

**Review by helmuthdu — APPROVED** [review]
Hey @AvinashReddy3108,

Thank you very much for your contribution, looks great so far.
Just one question, is this PR still WIP or it can be merged?

**Comment by AvinashReddy3108** [comment]
> Hey @AvinashReddy3108,
> 
> Thank you very much for your contribution, looks great so far.
> Just one question, is this PR still WIP or it can be merged?

I'll let you know when it's ready to merge.

Reason: I tried it on my VM, but it spit out all values as a single item, not as an array. This breaks the `select` part.

**Comment by AvinashReddy3108** [comment]
Hey @helmuthdu , I think my newer commits might have fixed the issue faced [here](https://github.com/helmuthdu/aui/pull/444#issuecomment-704709806).

**Review by helmuthdu — APPROVED** [review]

**Comment by helmuthdu** [comment]
I tried here and it did not work, I could not see any list of countries to select. So I reverted.

**Comment by AvinashReddy3108** [comment]
> I tried here and it did not work, I could not see any list of countries to select. So I reverted. Could you check again and create a new PR?

Sure :)

**Pull request merged**
